export const MetaFormTranslations = {
  en: {
    tokenAddress: "Token Address:",
    enterAddress: "Enter Address",
    ownershipConfirmed: "Ownership has not been Confirmed",
    image: "Image:",
    uploadImage: "Upload Image",
    uploadImageDesc: "128x128 pixels,100KB or less, png file",
    description: "Description:",
    descriptionDesc: "Put the description of your Token",
    check: "Check",
    addLinks: "Add Social Links & Tags",
    addLinksDesc: "Add links to your token metadata",
    website: "Website:",
    websitedesc: "Put your Website:",
    twitter: "Twitter:",
    twitterdesc: "Put your Twitter:",
    telegram: "Telegram:",
    telegramdesc: "Put your Telegram:",
    discord: "Discord:",
    update: "Update",
    fee: "Fee",
    discorddesc: "Put your Discord:",
    pleaseWait: "Please wait",
    loadingFee: "Loading fee configuration...",
    invalidImageFile: "Invalid image file",
    imageTooLarge: "Image must be ≤1MB",
    connectWalletFirst: "Connect wallet first",
    enterTokenAddress: "Enter token address",
    metadataImmutable: "Metadata is immutable – cannot be updated",
    notUpdateAuthority: "You are not the update authority for this metadata",
    verifiedReadyUpdate: "Verified – ready to update metadata",
    mintAuthorityRevoked: "Authority has been revoked – cannot create metadata",
    notMintAuthority:
      "Your connected wallet is not the authority – cannot create metadata",
    noMetadataFound: "No metadata found – ready to create metadata",
    invalidTokenOrAuthority: "Invalid token or authority mismatch",
    verificationFailed: "Verification failed",
    verifyTokenFirst: "Verify token first",
    descriptionRequired: "Description required",
    nameSymbolRequired: "Name and symbol required for creation",
    imageRequired: "Image required for creation",
    imageUploaded: "Image uploaded",
    metadataJsonUploaded: "Metadata JSON uploaded",
    operationFailed: "Operation failed",
    pleaseConnectWallet: "Please connect your wallet",
    checking: "Checking...",
    success: "✅ Success",
    error: "❌ Error",
    name: "Name",
    symbol: "Symbol",
    nameCannotUpdate: "Name (Cannot Update)",
    symbolCannotUpdate: "Symbol (Cannot Update)",
    processing: "Processing...",
    createMetadata: "Create Metadata",
    copy: "Copy",
    copied: "Copied to clipboard!",
    viewOnExplorer: "View on Solscan Explorer",
    txSuccess: "Transaction Successful",
    txFailed: "Transaction Failed",
    txSignature: "Transaction Signature",
    ok: "OK",
  },

  ko: {
    txSuccess: "거래가 성공적으로 완료되었습니다",
    txFailed: "거래에 실패했습니다",
    txSignature: "트랜잭션 해시",
    ok: "확인",
    copy: "복사",
    copied: "클립보드에 복사되었습니다!",
    viewOnExplorer: "Solscan 탐색기에서 보기",
    invalidImageFile: "잘못된 이미지 파일입니다",
    imageTooLarge: "이미지 크기는 1MB 이하여야 합니다",
    connectWalletFirst: "먼저 지갑을 연결하세요",
    enterTokenAddress: "토큰 주소를 입력하세요",
    metadataImmutable:
      "메타데이터가 변경 불가능 상태입니다 — 업데이트할 수 없습니다",
    notUpdateAuthority: "이 메타데이터에 대한 업데이트 권한이 없습니다",
    verifiedReadyUpdate:
      "확인 완료 — 메타데이터를 업데이트할 준비가 되었습니다",
    mintAuthorityRevoked:
      "민트 권한이 제거되었습니다 — 메타데이터를 생성할 수 없습니다",
    notMintAuthority:
      "연결된 지갑은 민트 권한이 아닙니다 — 메타데이터를 생성할 수 없습니다",
    noMetadataFound:
      "메타데이터가 존재하지 않습니다 — 메타데이터를 생성할 수 있습니다",
    invalidTokenOrAuthority:
      "유효하지 않은 토큰이거나 권한이 일치하지 않습니다",
    verificationFailed: "검증에 실패했습니다",
    verifyTokenFirst: "먼저 토큰을 검증하세요",
    descriptionRequired: "설명은 필수입니다",
    nameSymbolRequired: "생성을 위해 이름과 심볼이 필요합니다",
    imageRequired: "생성을 위해 이미지가 필요합니다",
    imageUploaded: "이미지가 업로드되었습니다",
    metadataJsonUploaded: "메타데이터 JSON이 업로드되었습니다",
    operationFailed: "작업에 실패했습니다",
    pleaseConnectWallet: "지갑을 연결해 주세요",
    checking: "확인 중...",
    success: "✅ 성공",
    error: "❌ 오류",
    name: "이름",
    symbol: "심볼",
    nameCannotUpdate: "이름 (수정 불가)",
    symbolCannotUpdate: "심볼 (수정 불가)",
    processing: "처리 중...",
    createMetadata: "메타데이터 생성",
    pleaseWait: "잠시만 기다려 주세요",
    loadingFee: "수수료 설정을 불러오는 중입니다...",
    tokenAddress: "토큰 주소:",
    enterAddress: "주소 입력",
    ownershipConfirmed: "소유권이 확인되지 않았습니다",
    check: "확인",
    image: "이미지:",
    uploadImage: "이미지 업로드",
    uploadImageDesc: "128x128픽셀, 100KB 이하, png 파일.",
    description: "설명:",
    descriptionDesc: "토큰에 대한 설명을 입력하세요",
    addLinks: "소셜 링크 및 태그 추가",
    addLinksDesc: "토큰 메타데이터에 링크 추가",
    website: "웹사이트:",
    websitedesc: "귀하의 웹사이트를 넣으세요",
    twitter: "트위터:",
    twitterdesc: "트위터를 넣어주세요",
    telegram: "텔레그램:",
    telegramdesc: "전보를 넣어",
    update: "업데이트",
    fee: "수수료",
    discord: "디스코드:",
    discorddesc: "당신의 불화를 넣어",
  },
};
