export const MetaFormTranslations = {
  en: {
    tokenAddress: "Token Address:",
    enterAddress: "Enter Address",
    ownershipConfirmed: "Ownership has not been Confirmed",
    image: "Image:",
    uploadImage: "Upload Image",
    uploadImageDesc: "128x128 pixels,100KB or less, png file",
    description: "Description:",
    descriptionDesc: "Put the description of your Token",
    check: "Check",
    addLinks: "Add Social Links & Tags",
    addLinksDesc: "Add links to your token metadata",
    website: "Website:",
    websitedesc: "Put your Website:",
    twitter: "Twitter:",
    twitterdesc: "Put your Twitter:",
    telegram: "Telegram:",
    telegramdesc: "Put your Telegram:",
    discord: "Discord:",
    update: "Update",
    fee: "Fee",
    discorddesc: "Put your Discord:",
    pleaseWait: "Please wait",
    loadingFee: "Loading fee configuration...",
  },
  ko: {
    pleaseWait: "잠시만 기다려 주세요",
    loadingFee: "수수료 설정을 불러오는 중입니다...",
    tokenAddress: "토큰 주소:",
    enterAddress: "주소 입력",
    ownershipConfirmed: "소유권이 확인되지 않았습니다",
    check: "확인",
    image: "이미지:",
    uploadImage: "이미지 업로드",
    uploadImageDesc: "128x128픽셀, 100KB 이하, png 파일.",
    description: "설명:",
    descriptionDesc: "토큰에 대한 설명을 입력하세요",
    addLinks: "소셜 링크 및 태그 추가",
    addLinksDesc: "토큰 메타데이터에 링크 추가",
    website: "웹사이트:",
    websitedesc: "귀하의 웹사이트를 넣으세요",
    twitter: "트위터:",
    twitterdesc: "트위터를 넣어주세요",
    telegram: "텔레그램:",
    telegramdesc: "전보를 넣어",
    update: "업데이트",
    fee: "수수료",
    discord: "디스코드:",
    discorddesc: "당신의 불화를 넣어",
  },
};
