export const MintTokenTranslations = {
  en: {
    tokenAddress: "Token Address:",
    enterAddress: "Enter Address",
    ownershipConfirmed: "Ownership has been Confirmed",
    check: "Check",
    amount: "Amount:",
    enterAmount: "Enter Amount",
    minting: "Minting",
    bin: "Bin",
    fee: "Fee 0.1SOL",
    mintingOwnership: "Minting Ownership:",
    enterID: "Enter ID",
    deletesMintingAuthority:
      "Deletes the authority to issue additional information.",
    revocation: "Revocation",
    burnOwnership: "Burn Ownership:",
    removesBurnPermission: "Removes permission to burn tokens.",
  },
  ko: {
    tokenAddress: "토큰 주소:",
    enterAddress: "주소 입력",
    ownershipConfirmed: "소유권이 확인되었습니다",
    check: "확인",
    amount: "수량:",
    enterAmount: "수량 입력",
    minting: "민팅",
    bin: "휴지통",
    fee: "수수료 0.1SOL",
    mintingOwnership: "민팅 소유권:",
    enterID: "ID 입력",
    deletesMintingAuthority: "추가 발행 권한을 삭제합니다.",
    revocation: "폐지",
    burnOwnership: "소각 소유권:",
    removesBurnPermission: "토큰 소각 권한을 제거합니다.",
  },
};
