// translations object from your original file, unchanged
export const tokenFormTranslations = {
  en: {
    name: "Name:",
    enadd: "Enter Address",
    nameplace: "Enter name of the token",
    symbol: "Symbol:",
    symbolplace: "Enter the Symbol of the token",
    decimals: "Decimals:",
    decimaldesc: "Most meme coin use 6 decimals",
    supply: "Supply:",
    supplydesc: "Most meme coin use 10B",
    image: "Image:",
    uploadImage: "Upload Image",
    uploadImageDesc: "Most meme coin use a squared 1000x1000 logo",
    description: "Description:",
    descriptionDesc: "Enter the description of your Token",
    addLinks: "Add Social Links & Tags",
    addLinksDesc: "Add links to your token metadata",
    website: "Website:",
    websitedesc: "Enter your Website:",
    twitter: "Twitter:",
    twitterdesc: "Enter your Twitter:",
    telegram: "Telegram:",
    telegramdesc: "Enter your Telegram:",
    discord: "Discord:",
    discorddesc: "Enter your Discord:",
    advancedOptions: "Advanced Options",
    modifyCreator: "Modify Creator Information",
    modifyCreatorDesc:
      "Change the information of the creator in the metadata, by default it is SOL TOOL.",
    revokeAuthorities: "Revoke Authorities",
    revokeFreeze: "Revoke Freeze",
    revokeFreezeDesc:
      "Freeze Authority allows you to freeze token accounts of holders.",
    revokeMint: "Revoke Mint",
    revokeMintDesc:
      "Mint Authority allows you to mint more supply of your token.",
    revokeUpdate: "Revoke Update",
    revokeUpdateDesc: "Update Authority allows you to update token metadata.",
    revokeAuthoritiesDesc:
      "Solana Token have 3 authorities: Freeze Authority, Mint Authority and Update Authority. Revoke them to attract more investors.",
    createToken: "Create Token",
    totalFees: "Total Fees :",
    creatorName: "Creator Name:",
    creatorWeb: "Creator Website:",
    createNamePlace: "CoinFactory",
    createWebPlace: "https://coinfactory.app",
    personalization: "Personalization",
    claim: "Claim a custom address",
    personalize:
      "Personalize your token contract address by customizing the beginning or end-stand out with a unique touch! ",
    prefix: "Prefix",
    suffix: "Suffix",
    max4: "Max 4",
    enable: "Enable",
    pump: "...PUMP",
    pumpfront: "PUMP...",
    addGen: "The address has not been generated yet",
    gend: "Generate Address",
    paraprocess:
      "Processing time! in some cases, generating a 4-characher address may take up to 1 hour.",
    nameTooltip:
      "Token name is visible in metadata and try to be unique and ≤ 50 characters.",
    nameExceedLengthError: "Token name cannot exceed 50 characters.",
    symbolTooltip:
      "Token symbol is visible in metadata and try to be unique and ≤ 10 characters.",
    symbolExceedLengthError: "Token symbol cannot exceed 10 characters",
    decimalTooltip:
      "If a token has 6 decimals, then 1 token = 1,000,000 smallest units.",
    decimalError: "Token decimals should between 1-12",
    supplyTooltip: "Intial supply is minted to creator of the token.",
    descriptionTooltip:
      "This description appears in the token metadata and explains the purpose of your token.",
    imageTooltip:
      "Upload a token logo. This image appears in wallets and explorers.",
    Change: "Change",
    Remove: "Remove",
    creatorAddress: "Creator Address",
    enterAddress: "Enter Solana address (optional, defaults to your wallet)",
    removeOption: "Remove creator information",
    removeCreatorTooltip:
      "By selecting the option the metadata remove the creator field completely",
    maxLength4: "Maximum Length should be less than 4",
    generating: "Generating...",
    generatedAddress: "Generated Address:",
    accdel: "Account Deletion Fee Refund Designation",
    accdesc:
      "When a token account is deleted from the user's wallet, specify the wallet to which the rent will be refunded",
    soltool: "SOL Tool",
    accOwner: "Account owner",
    tokenCreator: "Token Creator",
    customAddress: "Custom Address",
    tokenCreating: "Creating token...",
    connectWalletFirst: "Please connect your wallet first.",
    vanityLengthError:
      "Combined prefix and suffix length should not exceed 8 characters.",
    vanitySuccess: "Vanity address generated successfully!",
    vanityTimeout:
      "Could not generate vanity address in reasonable time. Try shorter prefix/suffix.",
    vanityGenError: "Error generating vanity address:",
    vanityFailed: "Failed to generate vanity address.",
    fillAllFields:
      "Please fill in all required fields: name, symbol, image, and description.",
    noCloseAuthority: "No token creator defined for close authority.",
    invalidRefundAddress: "Invalid custom refund address.",
    tokenCreateFailed: "Failed to create token.",
    pleaseWait: "Please wait",
    loadingFee: "Loading fee configuration...",
    tokenDetails: "Token Details",
    invalidImageFile: "Invalid image file",
    imageTooLarge: "Image file should be less than or equal to 1MB",
    invalidAdvancedCreator: "Invalid Advanced Creator fields values",
    invalidCreatorAddress: "Invalid creator address",
    tokenCreated: "Token Created Successfully!",
    mintAddress: "Mint Address",
    copy: "Copy",
    copied: "Copied to clipboard!",
    viewOnExplorer: "View on Solscan Explorer",
    startStage: "Start",
    createStage: "Create",
    uploadImageStage: "Upload Image",
    prepareMetadataStage: "Prepare Metadata",
    uploadMetadatStage: "Upload Metadata",
    confirmTxStage: "Confirm Tx",
    note: "NOTE: ",
    tokenCreationInvolves: " Token creation involves ",
    walletApprovalText:
      " wallet approval transactions, depending on the options you select (metadata, minting, authority revocations, etc.). In addition to the SolTool service fee, a small Solana network (gas) fee will be charged for each transaction. Please ensure your wallet has sufficient SOL balance before proceeding.",
  },
  ko: {
    note: "안내: ",
    tokenCreationInvolves: " 토큰 생성 과정에는 ",
    walletApprovalText:
      " 선택한 옵션(메타데이터, 민팅, 권한 해제 등)에 따라 3~6회의 지갑 승인 트랜잭션이 필요합니다. SolTool 서비스 수수료 외에도 각 트랜잭션마다 소량의 Solana 네트워크(가스) 수수료가 부과됩니다. 진행하기 전에 지갑에 충분한 SOL 잔액이 있는지 확인해 주세요.",
    startStage: "시작",
    createStage: "생성 시작",
    uploadImageStage: "이미지 업로드",
    prepareMetadataStage: "메타데이터 준비",
    uploadMetadatStage: "메타데이터 업로드",
    confirmTxStage: "트랜잭션 확인",
    tokenCreated: "토큰이 성공적으로 생성되었습니다!",
    mintAddress: "민트 주소",
    copy: "복사",
    copied: "클립보드에 복사되었습니다!",
    viewOnExplorer: "Solscan 탐색기에서 보기",
    invalidImageFile: "유효하지 않은 이미지 파일입니다",
    imageTooLarge: "이미지 파일은 1MB 이하이어야 합니다",
    invalidAdvancedCreator: "고급 창작자 필드 값이 올바르지 않습니다",
    invalidCreatorAddress: "유효하지 않은 창작자 주소입니다",
    tokenDetails: "토큰 세부 정보",
    pleaseWait: "잠시만 기다려 주세요",
    loadingFee: "수수료 설정을 불러오는 중입니다...",
    connectWalletFirst: "먼저 지갑을 연결해 주세요.",
    vanityLengthError: "접두사와 접미사의 총 길이는 8자를 초과할 수 없습니다.",
    vanitySuccess: "바니티 주소가 성공적으로 생성되었습니다!",
    vanityTimeout:
      "합리적인 시간 내에 바니티 주소를 생성할 수 없습니다. 더 짧은 접두사/접미사를 시도하세요.",
    vanityGenError: "바니티 주소 생성 중 오류:",
    vanityFailed: "바니티 주소 생성에 실패했습니다.",
    fillAllFields:
      "필수 항목을 모두 입력해 주세요: 이름, 심볼, 이미지 및 설명.",
    noCloseAuthority: "종료 권한에 대한 토큰 생성자가 정의되지 않았습니다.",
    invalidRefundAddress: "유효하지 않은 사용자 정의 환불 주소입니다.",
    tokenCreateFailed: "토큰 생성에 실패했습니다.",
    tokenCreating: "토큰 생성 중...",
    soltool: "SOL 도구",
    tokenCreator: "토큰 생성자",
    customAddress: "사용자 정의 주소",
    accOwner: "계정 소유자",
    maxLength4: "최대 길이는 4보다 작아야 합니다",
    generating: "생성 중...",
    generatedAddress: "생성된 주소:",
    removeCreatorTooltip:
      "이 옵션을 선택하면 토큰 메타데이터에서 크리에이터 필드가 완전히 제거됩니다.",
    creatorAddress: "크리에이터 주소",
    enterAddress:
      "솔라나 주소를 입력하세요 (선택 사항, 기본값은 지갑 주소입니다)",
    removeOption: "크리에이터 정보 제거",
    Remove: "삭제",
    Change: "변경",
    imageTooltip: "지갑과 탐색기에 표시될 토큰 로고를 업로드하세요.",
    descriptionTooltip:
      "이 설명은 토큰 메타데이터에 표시되며 토큰의 목적을 설명합니다.",
    supplyTooltip: "초기 공급량은 토큰 생성자에게 민트됩니다.",
    decimalError: "토큰 소수점 자릿수는 1에서 12 사이여야 합니다.",
    decimalTooltip:
      "토큰에 소수점이 6자리라면, 1토큰은 가장 작은 단위 1,000,000개와 같습니다.",
    symbolExceedLengthError: "토큰 심볼은 10자를 초과할 수 없습니다.",
    symbolTooltip:
      "토큰 심볼은 메타데이터에 표시되며, 고유해야 하고 10자 이하여야 합니다.",
    nameExceedLengthError: "토큰 이름은 50자를 초과할 수 없습니다.",
    nameTooltip:
      "토큰 이름은 메타데이터에 표시되며, 고유해야 하고 50자 이하여야 합니다.",
    name: "이름:",
    enadd: "주소를 입력하세요",
    nameplace: "토큰 이름을 입력하세요",
    symbol: "심볼:",
    symbolplace: "토큰의 심볼을 입력하세요",
    decimals: "소수점 자리:",
    decimaldesc: "대부분의 밈 코인은 소수점 6자리를 사용합니다.",
    supply: "공급량:",
    supplydesc: "대부분의 밈 코인은 10B를 사용합니다",
    image: "이미지:",
    uploadImage: "이미지 업로드",
    uploadImageDesc: "대부분의 밈 코인은 1000x1000 정사각형 로고를 사용합니다.",
    description: "설명:",
    descriptionDesc: "토큰에 대한 설명을 입력하세요",
    addLinks: "소셜 링크 및 태그 추가",
    addLinksDesc: "토큰 메타데이터에 링크 추가",
    website: "웹사이트:",
    websitedesc: "귀하의 웹사이트를 넣으세요",
    twitter: "트위터:",
    twitterdesc: "트위터를 넣어주세요",
    telegram: "텔레그램:",
    telegramdesc: "전보를 넣어",
    discord: "디스코드:",
    discorddesc: "당신의 불화를 넣어",
    advancedOptions: "고급 옵션",
    modifyCreator: "창작자 정보 수정",
    modifyCreatorDesc:
      "메타데이터에서 작성자의 정보를 변경합니다. 기본값은 SOL TOOL입니다.",
    revokeAuthorities: "권한 취소",
    revokeAuthoritiesDesc:
      "솔라나 토큰에는 3가지 권한이 있습니다: 동결 권한, 민트 권한, 업데이트 권한. 더 많은 투자자를 유치하려면 권한을 취소하세요.",
    revokeFreeze: "프리즈 권한 취소",
    revokeFreezeDesc:
      "동결 권한을 사용하면 토큰 보유자의 토큰 계정을 동결할 수 있습니다.",
    revokeMint: "민트 권한 취소",
    revokeMintDesc:
      "Mint Authority를 사용하면 더 많은 토큰을 주조할 수 있습니다.",
    revokeUpdate: "업데이트 권한 취소",
    revokeUpdateDesc:
      "업데이트 권한을 사용하면 토큰 메타데이터를 업데이트할 수 있습니다.",
    createToken: "토큰 생성",
    totalFees: "총 수수료 :",
    creatorName: "작성자 이름",
    creatorWeb: "제작자 웹사이트",
    createNamePlace: "CoinFactory",
    createWebPlace: "https://coinfactory.app",
    personalization: "개인화",
    claim: "사용자 정의 주소 청구",
    personalize:
      "토큰 계약 주소를 시작이나 끝 부분을 맞춤 설정하여 개인화하고 독특한 터치로 돋보이게 하세요!",
    prefix: "접두사",
    suffix: "접미사",
    max4: "최대 4개",
    enable: "~할 수 있게 하다",
    pump: "...품다",
    pumpfront: "품다...",
    addGen: "아직 주소가 생성되지 않았습니다",
    gend: "주소 생성",
    paraprocess:
      "처리 시간! 어떤 경우에는 4자리 주소를 생성하는 데 최대 1시간이 걸릴 수 있습니다.",
    accdel: "계정 삭제 수수료 환불 지정",
    accdesc:
      "사용자 지갑에서 토큰 계정이 삭제되는 경우, 입금금이 환불될 지갑을 지정해주세요.",
  },
};
